version: "3.4"
services:

  php:
    build: ./docker/php
    container_name: ${PROJECT_NAME}-php
    volumes:
      - ${APP_PATH_LOCAL}:/var/www/app:cached
    links:
      - db

  nginx:
    image: nginx:1.15.10
    container_name: ${PROJECT_NAME}-nginx
    volumes:
        - ${APP_PATH_LOCAL}:/var/www/app:cached
        - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./docker/nginx/general.conf:/etc/nginx/general.conf:ro
        - ./docker/nginx/sites-enabled:/etc/nginx/sites-enabled:ro
        - ./logs/nginx/:/var/log/nginx
    links:
        - php
    ports:
     - ${NGINX_PORT}:80

  db:
    container_name: ${PROJECT_NAME}-mysql
    image: mysql:8.0.15
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./docker/mysql/dump:/var/lib/mysql
      - ./docker/mysql/conf/my.cnf:/etc/mysql/my.cnf:ro
    ports:
      - ${MYSQL_PORT}:3306
