version: "3.4"
services:

  php:
    build: ./docker/php
    container_name: ${PROJECT_NAME}-php
    volumes:
      - ${APP_PATH_LOCAL}:/var/www/app:cached
    links:
      - db

  nginx:
    image: nginx:1.15.10
    container_name: ${PROJECT_NAME}-nginx
    volumes:
        - ${APP_PATH_LOCAL}:/var/www/app:cached
        - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./docker/nginx/general.conf:/etc/nginx/general.conf:ro
        - ./docker/nginx/sites-enabled:/etc/nginx/sites-enabled:ro
        - ./logs/nginx/:/var/log/nginx
    links:
        - php
    ports:
     - ${NGINX_PORT}:80

  db:
    container_name: ${PROJECT_NAME}-mysql
    image: mysql:8.0.15
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./docker/mysql/dump:/var/lib/mysql
      - ./docker/mysql/conf/my.cnf:/etc/mysql/my.cnf:ro
    ports:
      - ${MYSQL_PORT}:3306

  rabbitmq:
    container_name: ${PROJECT_NAME}-rabbitmq
    image: rabbitmq:3.7.14-management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
      - ./docker/rabbitmq/dump:/var/lib/rabbitmq
    ports:
      - ${RABBITMQ_PORT}:5672
      - ${RABBITMQ_UI_PORT}:15672

  phpmyadmin:
    container_name: ${PROJECT_NAME}-phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
        - ${PMA_PORT}:80
    environment:
        - PMA_HOST=mysql

  maildev:
    container_name: ${PROJECT_NAME}-maildev
    image: djfarrelly/maildev
    ports:
        - ${MAILDEV_PORT}:80